[env]
TERM = "xterm-256color"

[window]
padding.x = 20
padding.y = 20

decorations = "Buttonless"
opacity = 0.92
blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 16.0

[keyboard]
bindings = [
{ key = "N", mods = "Alt", action = "CreateNewWindow" },
{ key = "C", mods = "Alt", action = "Quit" }
]
